# Generated by Django 5.1 on 2024-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_usuario_nombre_alter_usuario_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/juegos/'),
        ),
    ]
