# Generated by Django 5.1.1 on 2024-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_alter_lista_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
