# Generated by Django 5.1.2 on 2024-10-22 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director')], max_length=10)),
                ('foto', models.ImageField(upload_to='personas/')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('fecha_lanzamiento', models.DateField()),
                ('calificacion_rotten', models.DecimalField(decimal_places=1, max_digits=3)),
                ('trailer_youtube', models.URLField()),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas_dirigidas', to='pelicula.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=255)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparto_set', to='pelicula.pelicula')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.persona')),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='reparto',
            field=models.ManyToManyField(related_name='peliculas_actuadas', through='pelicula.Reparto', to='pelicula.persona'),
        ),
    ]
