# Generated by Django 5.1.2 on 2024-10-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='reparto',
            field=models.ManyToManyField(related_name='peliculas_como_actor', through='pelicula.Reparto', to='pelicula.persona'),
        ),
    ]
